package br.com.guifr.hackerrank.preparationkit.threemonth.weeksix;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class PalindromeIndexTest {


    @Test
    @DisplayName("Return 1 When PalindromeIndex With 'quyjjdcgsvvsgcdjjyq'")
    public void test1() {

        Assertions.assertEquals(1,PalindromeIndex.with("quyjjdcgsvvsgcdjjyq"));
    }

    @Test
    @DisplayName("Return 8 When PalindromeIndex With 'hgygsvlfwcwnswtuhmyaljkqlqjjqlqkjlaymhutwsnwcflvsgygh'")
    public void test2() {

        Assertions.assertEquals(8,PalindromeIndex.with("hgygsvlfwcwnswtuhmyaljkqlqjjqlqkjlaymhutwsnwcflvsgygh"));
    }

    @Test
    @DisplayName("Return 33 When PalindromeIndex With 'fgnf...'")
    public void test3() {

        Assertions.assertEquals(33,PalindromeIndex.with("fgnfnidynhxebxxxfmxixhsruldhsaobhlcggchboashdlurshxixmfxxxbexhnydinfngf"));
    }

    @Test
    @DisplayName("Return 23 When PalindromeIndex With 'bsyh...'")
    public void test4() {

        Assertions.assertEquals(23,PalindromeIndex.with("bsyhvwfuesumsehmytqioswvpcbxyolapfywdxeacyuruybhbwxjmrrmjxwbhbyuruycaexdwyfpaloyxbcpwsoiqtymhesmuseufwvhysb"));
    }

    @Test
    @DisplayName("Return 25 When PalindromeIndex With 'fvyq...'")
    public void test5() {

        Assertions.assertEquals(25,PalindromeIndex.with("fvyqxqxynewuebtcuqdwyetyqqisappmunmnldmkttkmdlnmnumppasiqyteywdquctbeuwenyxqxqyvf"));
    }

    @Test
    @DisplayName("Return 44 When PalindromeIndex With 'mmbi...'")
    public void test6() {

        Assertions.assertEquals(44,PalindromeIndex.with("mmbiefhflbeckaecprwfgmqlydfroxrblulpasumubqhhbvlqpixvvxipqlvbhqbumusaplulbrxorfdylqmgfwrpceakceblfhfeibmm"));
    }

    @Test
    @DisplayName("Return 20 When PalindromeIndex With 'tpqkn...'")
    public void test7() {

        Assertions.assertEquals(20,PalindromeIndex.with("tpqknkmbgasitnwqrqasvolmevkasccsakvemlosaqrqwntisagbmknkqpt"));
    }

    @Test
    @DisplayName("Return -1 When PalindromeIndex With 'lhrxvssvxrhl'")
    public void test8() {

        Assertions.assertEquals(-1,PalindromeIndex.with("lhrxvssvxrhl"));
    }

    @Test
    @DisplayName("Return 14 When PalindromeIndex With 'prco...'")
    public void test9() {

        Assertions.assertEquals(14,PalindromeIndex.with("prcoitfiptvcxrvoalqmfpnqyhrubxspplrftomfehbbhefmotfrlppsxburhyqnpfmqlaorxcvtpiftiocrp"));
    }

    @Test
    @DisplayName("Return -1 When PalindromeIndex With 'kjow...'")
    public void test10() {

        Assertions.assertEquals(-1,PalindromeIndex.with("kjowoemiduaaxasnqghxbxkiccikxbxhgqnsaxaaudimeowojk"));
    }

    @Test
    @DisplayName("Return -1 When PalindromeIndex With 'aprrmdeykho...'")
    public void test11() {

        String s = "aprrmdeykhorwsalkysinbvylgcgiaokrifgolfytvsqqufctxkjbijnonvapmkivrokewlasfskcxowyyiakrpyilyxbmgygxjkuwmpegcheqgdsogdjverkgpnuymbyxovublchqjojptegahpyojlucypdnqclfxijlkqevhoncsuedmftwsoytgchygsheeqrojwlrnbvivanjihibvjvelderylxderrnqffehdnfebqmlypjilovrspqgpvkipabvigflvkryegkdwuoklmcedumuqyfhyhfjpkvnwnmbuahtwxeikjopednxcsfdcmnrwlfvbuaxwhrthyeriskovxoasvdvisnhgveisggppblwapqkkbbiyqismnqvhgdnejxwrfohgaeirvuewvmyoutcjkassfixphuhmmruovfhtaltxysnvophbpatwjrmspwhcqcqmjahjobhpvulmmtnevjchcqarphvglmvwpfgeiqtenfsdbghxplhtdknstjciyxfofmsnfmtutmxvugvmrfhwpwsmjuukuabaovpvijrevpcqxadqgmpxmikvfhgcijcyfrvpdntydyrcyxuhmkiyvuwbdfenoimtdkjgxgiefaigxdonpwmltmpwrvkheadhkpqlvypbyxhadxnswchroyojucsyevjonaajyrmarwcuwpquuamlyduvhpulogdcidojxbmpaonxhescehpfknbudxgthjwpplcnoofpdsnmyiofphkcunwaoguvptnhfpwtgdlmxyyxjqdyxqeuedwujrqalhjswhpgmbskdrimiooifsdlvdhiuakjhtehbtnnxgbbajpjagtfyatxdbiabsjlmosqkggiohjotcatiuckuvkaysaclknabgqloxudfgsbisvtpxemtomuhnwualubtmojmjmtqhvbbruqrygnpsiwghriupjpcyboknkdvgfyacrrexhtrptaxnjudukhvlxhcjkapryswqkbrswlkqlkfwgkussqhqajanjsfklcdxfusdgetuqbtymoshicxilbvwtcjhgmfokyrsfnpvrkxgbsnjunsioofksqrcdxqpwijexyaplavnsjwnxpvohdaattcatspqdbwcbxroxqctcahargryjtcenegiavbdxyhbycrysusuwdxqjrqslsybyflyenfeomhpoyqjvkfspfkywdtixtlybxyhlencsuriwktsuymmgyldegnccabfxcnlidpcyjmvtgorideocsuiyimdkqkksxxcengdysbtyrnjvryaktjlevormaciabmeqsjqnkmofaybrxdftoqanirckwkmxytqrfjhsvwxvvbqvevrtorhykllhwbhvuaqckaugwsfutxqbvkumdemppayobinxigbugvegpjblhumffjrkpeaifbyijmhusipcetivdlkmgyrolkybqclxdlhnaqityaxfugearonbnhrbtsfnuqnbewofnybmyyuvhywbnmcdtvfqpkekdrnipcnfdosfppdwoaxemdhjyoaqbgcfarprudxatshjiliwngbbjkmlaocdugkuyanvflxyeikotsljcomnyyybnefkkpglqvhxjiapqkemgpvkejxfkahygojsgrfypoxywxopkscqkydqkewuegvkwiddakdsabryyjpjcrdpsggdkfbqnwdkhjoktrdvuuxtgnfjhibbrjgepjvfjbqqmhbjygftedpksuvbgwexhmcywaggewyqebafjibnlsyhoukuuouebydaaligjiwplxxugbjtukdlfngcedgicliexrkjcibniykqdtmxgqjogrqluxtyjeejvosxwunhvyxbunycgkqmejxbhtbtyfdutyvtvldrkcvirukxidkmmlowfpseuxcqwamslqnyujhmgtkowueliukokduhcwabynulekkyttncnxrmuxaeslufqpounowmetaiemjxgyavwtiutlbmyvtrlinbxkoeeqnkeyimbkjahtudfvsgtmygvmhvyxafpppvraismrsvoqavosdjferdqbbracwrtonloxgdscahscfjuiucomihojyqnxiioxtdvbjodjxxnehkodmerwlihlyuljdbhaggdpwgbvgqapbosounnhvwuvsgfxjpasxdiujmqrdqifidvdqlmnjhleqsccidugggcssumxoufyydcrprfbbsfrmjuumrevxiqqddrtbyscfxtwpaxqsdlhmifcajaytqryvjtwlmyqmvncxnvsshbfpgjprjqlcjmbugagvcyixonvcjouqpdivmapyrbdboevwhfujeghvtfxftvxmygkngboxesbuyasghprnvbjrgiwdeurfbcskfkkmdoheocnvsfjohthpegskckpfpkpwubjaprfgtscoanejjnantuxxipexdtwxwhyoygwubykbpqnygnncknbsghsjbqhbxiryqptrqgvgyjgfyvkjlldrsvdvolymvrlnhifaqdhqopxnniayvftqdwpskohhiturecswianwronfwpetuxkaxasirbpawmsdrncapqyhfmmeesxyrlcpnuxhxqkwdfcwsfwixypfncjsuktoxvgnthvtagtdnvdgdaodbgipkuihfewfbfsuoqooykumjxumalqcrbrcvckdgjkjqgggwvuyipnrnjfouxqnbkraoedwnqjfwpnvniuwblooutfptxfvkxvycbystiaqanpoxklyvaqswvlsuqqfqmhvqiomsqesethegsefvuxsqlnndfvvrdrknixgyeyfahmicqnxnosgchufmqcgvvtjhtpgxqoaadidtydhpwprgkasdebbaumhoeqovhqvkaygbdpscfmisobxscavamfqrxgnhwlrynacqpwuxkdqygoukqqkevcxwknejywjmynfrlapxfiwlytwqkjwjnugxkkkjjtyjjeduhsumdubeoxuajtjaqrxbcinoeoaqsdncxjpdeshsqfucyecsxdvdnjruxrltwbxuknxoifkymfemmihkldncnhwnbkjxliuyxunhdaipgmeuxlhjpxlffksjwfhjnfilaxufyevhsaeqmldcjqjrccbyhikwpujstgxuktegwiwjvangrwxvbywljiicftuybsvnnctkkrvhtlpnknjlohyaricwewyfqwvgapsmjqveclrobecpncsfmuequdylbutdkmpwfmdhxuxabarocmvqibifghqjemoqbfngrqprontrnohsbfjlitqrdjbhvsywxodrgsjwieowsxrvedimabedlinjbmjbdmsjiciqixpdvjaapkppltuyeijhusiyhbkretlmtbqrnssddkuqgpqlycsvwcugdiyjekwxnprbimgnwbeerwpsykoxomfsugcbsbbgsskbgsqduvjoubhumvubkcvhiyibcjkvfuylnqqkobbjckgqjcsteqcppkquwbsexrpokibyldlonrhyvctbtvsjijghnylntdcemegxjroyjwygysjsqcfbnnjdnurjbtnnatnjnfjxcigddpyttguhtgljcfsfyjscfintnytrjavmrwgndeuykijonetpporxxhrnhngqpeejbmwestfedousvringclgkfursbikhotieqowltdqlbjhsswbujihofyiikupbpafiofviimvjyferdgomqwbxxlgkhxmyxtjoygwkutvtbbnejdqccuacginpicqixbwajtkepiytjoxurryvmyyujoltsecqfyqovdvlmwfxlgtgxsckudfgrsbkxdefduwyysmlrujddflbbonvruemofwolbvqysrxnglhdwlgdwjenwcisiujoracvvsupmufsinwfbfiapoomswhcrsslswjppehcbmwjctpdaagrruektoonhjbbglsxractoafrvwwxxdppawcvltludnxkyqksqnognualrykrdcjfyocminildgxexjxqymyohyacyktepgloupcdemqjsrosdmkcbjqllqnmejstrekmumrbblkudyninakpkddxvskccdxuhjjexcfapqwurmdinpaaudxqvkvaptwyfhegljibcfxutbdhsfjnijegtaglwelenpkybsceaaywdegvlqjtcpaysikpmvtanhbpcftfhuckbigmbrgeiidbqnsgmmiavkpyrjeaegkfqtrulayvkewcrpkgfshbdwaxjgxnokviendsqcobgofaepjljqpoppmyyknnvlvcbburdmvlbbohtxvdolredhgcrtsphquispbxeykfabptylypwtvabcfuxxnfoiojxrifqsksvcpunomkkinlnsjlswtjfktfcckuwvpsafpowcbhmqvajfoeciohskmwmxrlvhgvpxmmcovofrrrwgvyqmglwvilvcytlhrbffpjvmbdgswebvdtimfikntgpvcddtfjywuwlvbsoxwrtclfqqnbghjxflcjgjuhgpfsmglbgkvbmhggythfdtgjfiunrpvafbsrjgvpsrqiyyoauxibromawhnqwjqekmwtuumqodyndpqanybipniouvhtixyumxpkscbhhcwmrpnhqqpgfawcyewhdxcrvtcqxdxifwuynkhecynjcknbpmkukmmijpyhuyrdwpemalqeneprreshqfceromdgmnelfhkunwxaqcpwuhobcxthaxbrlfxauenanyxcxveqatoudfvhesoeqrveywgtbuwpvurvsvnurcqwjoenhuubmshopoktjhlfefdydquuunrfexsospphjwvblhuwqievniwqyrnufhakfuyalqiupexenvbfegduqalpucmclmmrknrxgcswhsbwoeetkjobmcthggjsvykioegvhyuqtxpjcudpetsqxmxfvkxrjkcaqivajsqdqhmterjileakrarpmrjxelyutwvdqoghxtdclonatpmnpedfxmdcxcyrawusmdcmwirlwflsuxgmelrcxxgxafpcdmwrqaepixbhdobaojnsvhwvfduilmmoakgskmiulmcqbfrqphlnoljwqefcrtqteymqowlajqqlvkenrrbjdngutnwnhqjorvfgttgdkaqimuyfncqspynmmnavgkkxisfemnkypbhdygkojbhbcxnonqmtdarnsyshndgfgpihyuvkxelaecqruelagfnyhiiwnocwgnefibphhejnibffhsfnxuofgwcvnhstuxcdbrmkxyxiafnjxuwxqngymkuarqvoqxursheqgecilprjlqjeepfqdaswqpmhnhbiqhcaneiytdihtunyksrpvlnobayqhcaakcaaglacokmifajsveirpxgsxhjhkliwpkwxvwbkkpvpphkllvfbtovuvicgtmdkxbktalhkbddtkphylncgeybahfjdsopsrbmsovfsykombvlolpupoxsxgcebsttlwiemflhgwvsatgogwmxnmsmswqtqmpckyiygvimseiuaqkgnyhelcqhajdsxtwiufjbdrnyxxtypghffqjrtcyvlcqkvnusuhtxbkwcitbaakggcpxxswvgboqacosyxpyyawbkqenqptwtjwtevrlxgeaiusjskiumhvaxdnruhqosokamclmirmsnicismdgucgsftmadgqvwbvjfjwpejitrmcnyittkaprverykkwhnvrsfqilcsfwfkkgsedfguwcyqbmbxtotnhcernjkvgpgqxbwbgdvfhxvkkyignfuwjbqykbussdlqgkumpqtwqrhbqsigxffjgvityeorjblqlgfcyabqrjrlecrehanqvvmvabpmebdshiuhkxadhrqnwkrekfwjcjhenwqrbtkkfhtpgtupolelwvrjepsgbcmocejdatpfekvmeqcsfieehwnlojrplgfpkounkluovqbakgvrqavxyjjnsdghklywcukmggecyhelpadhdyfelpuesbnfondqipfqxjuxtyjjcpqhownaoihjlwpcmuswkbnjkijekuqmkhvcejesundglujxpexcfllswwyhspvdathedmaxafhnasopymthxiaufbextcetvlxaaaabfjqfefwertlscnphquikwoevcfxdfxgnkwuoduuwogpqvganbkxayfvckthrunfhmdxrxtpmcffylfoosorrtpvgkdyhsgqgloajipxnvdmjldbersxoiuuuxvetfucqkcbusbiqfwcsadyuvwjhtgcudjoieqbqsemlguenshgskhpjgysbguvlgkvldwcvcokkmqxfxgalpqwvrpwxmultfhfkfjjjbvvnmtuncubrnxngnngaisvqcdbhnmsqioexkylmvmgkmwsakycutylwcpgrcainqolcpyqmnayawrajseendqmiiscmunaoensumjhajgaiacrshwgmpuwxocmlpnctbuqqfxqqgtagxtchqkuigtiwvvinllkmibfncwhisjrqdtywgvhmrqjomuexiomqqshurofmayffugeccmowdynrvrpejeuaycwsscfucnbwtfyyrovupjoldgpmlmomplgkongqbjnxopwjeugvevhhcyupljddvlomywddgsbwkagqupmbltkpsfghrjkpuycvxhbeceengmebctepppglwmsqxdgufksdtukybomibslgoqvfgcqfqjwoofjtqdamaklbbajctxkkohpwlgcdryrjfedxjdkjpwmqwyvswgelnvkafmdwowivdmtmrgvkdlbdkwvjgcwtyhvetbdkbmgebcrujpfmbjrngqwostjtbhaxjgkksrqvviqfyyucimqqdpgwkrsnytnkaywusosoyluxkpducvoglufvoamptadvycsrqlhsxesktvixrwgetlckmoairffqialbmutmynysjhsegaialmkaenjvsqobqadfwytvmtqydkdkknkxcxyglkegdtkvvpetoxperjdvtiigvseasfhgplnufarepxxgvpkqbpmuxubvpiwlngrgrhbahugysegpvsgxjuujrygjhfuulpbfyfhjanivtqlqmtqvqlhkkpvtutrijsqkaatbofwkxkdkgtiyiqjugfpeyhokchvdirgywdjvpngvjpwrignonfupokcstxvcqebpjnlybuwkmtfuculschiqtkjnlisemttwhixkdvxrrdmwaapchxsdketxomceiydsjbdoydgtgsqiugkdgfiqmepbqtfcukueoasneyjmtavpgguomfgykxcdtkfpuctjdnajojvjmtbubvkpbsqlqurmfwcdaymfmoodbmmnhpiklscplsdepurvuvywuncjfsnghctoscbgvdvjxaoowikreloabsjgnyovcimwnodlrauqcjfbtrtydkyggkptmepopdldroolqjcuvhwpbqqedrnjddepjvgybtcsksfcfjwdttsumkcqcpchuiyefhegbicmejqjspmmmhkytmryeuiydidkrhrtstiwdbixqunfexfbkyaovincssmlbghvcruhudgnattgtbhechuysiblbpyeyicbcwlyctncpjjjksnobkntuqhxjjfithlyhwxjqlogwarhsfwvrmpmgalplqafxlehldreqinoifxdnwafmrssreidwklwvpfhuyoohcdrhduudwdppvihcsnydyxbqdloeadncgflldhocmeriocmhrnmqlojraxvabkejrpvuymxlrrvitislxfekvqcvoxxskecdwaavnakhsgporkdpqhcmxelpflipqmunpvlfxvmqfeiyploistutxijfutxlisbxqmdpjrgoyqpoceyvavryfdgayenhaogqbjgkepbdgqtjxshxobyteivdmjmmxsgcfomjgqonjiyjdiirljoprmuhwhvwdcyitotahinqqobvylnkwecrryyqhunmaputeqtlykerbhnbudnsiqkcplsygilixieebyralwtoejrcpguayhcqswsbfemgpqkqrdtfcpuicmkruhrtovljsenakagcstvnyrsbjnjldwdxewuvsgflmumywueqoaentyqdnbpsxuqeslaltgaidmkbhotyqaokygpmjhfhdynxmojhujraxcbiqujjuxvwemjntrwwslwfahowshwtlbefxnovllssaegtvgtqrqwtanqvwprjsvqrjfnwsgpsmwpjdjcwayqdpjymysvsommauawpinjumygrkjomkfpcqqppjnkadyaayxpjlbhxcppmygcmnroelgtwuhxagxaivptjtbjvrblshnhuhyysfvqcfqcnocvnuqwotjmlkxhunopvnrovphxuxbipfhdaaaqvlgkwerrsijqwdfuspsppvbfciieklxgyeqvkkpftavsdenytgoldprhacnmplvpponbaegtefmjjcifiaqnpkwsplfhwbwpqnssrymxgbhpdsunsoekbbfqolymoxchlucdvobfrluwgsnbjtnkutckhbyxydgnakqxcudtibtqtjrfdfpabtmiwlhwqpksadrcxuyixsyteqyhyphalwjjksicisukxmnykmhihjdlceubveeibprmiaosuldsbqtnfcxondapiwrecvmdnepvggoburwvlqjquhgiliytisakqnnetgaboqejibfvsqnnbvymgxiqskbjxrnuapxogcyqggnyadobbppjpabikerlvhgxygnhiobowqpwthxwynipnlxbqsmocsncydljrmbqdsoycovcfhrusrvjkibndorerdolsrcvkqvpgtrnbliwdfiqnjgrxavrdmdveiuryqhhmbwqmgnrlviygosgoryueeslmpdoikxvlvmacarnxdoetkllcmigsbtgrwwcjuxwsmwumrknucroofaqtiynmttgssidnjajvaglrryovsdkygdsqcifxenrwyuniwwewdrqwsfumlfntiiknrsnvgftfchpagwyjoqjivewhkkbusokkhyhpgdxjmnjskiecbnmxsjhftjamanajmjysmyebnptabxccooahxkmrtohvchfqsgmfgqitjcvkcymsppaoaoiverriyycrfqyljhhsledqfsjuimjibuehmxsowuiclkqwtaqgetylokhwwshbnnkdldrkaapnkglfgcnnxoynyimycuarimuwqmhqnwhafsfowucwjdkjmakqukifwecpqmjglqjtlqiimmhxrshestwpgguekavdohmaxvvlmevbsealyjrtepjkvgqiipnwwaavxvjndgqvmqjldcfhtqtrylaibphxsjvqiignoxlbovorxvbtmvlnjlvkbgktrjnartnitcljxcdxxhrmddamqyytflqwweaqapyurmgrolpmshyxmamdbnxgcqfywhqwartrfckvqcllkkkymydnndvrteqqlhpncmghqsfhwqtjegjqhmhwrfonjggxpvlrktbcohlmxhvcpfvxtfulkkbwshuiggdqdeurnjemqdqhimfftasfmucfcyoifrakxwdmgjbxmrhxhmdbovicqkjtjxerrecsehfkrgkearehghlxgtcwhlssmxmeepwiyevqkixndcujmijsdlpmxlfmjsqpkqyjuwdifbvifsurcekhqdtqoyfatvpeoqqmntwtwucenywrejywmspbuudqstxkkowykvujqyngykyfwxcjttnqoqjjkhtvxswkotthskotwnytnbejutclkmxvvrtunshcmckhobclobgefmocgsqshooegkbtfiytklcbmendhvhmkxrqrijywbdfnecvpbpcorebxregpnuammsgueftflavrcrhfjktcoucibiaogabsshqwpkfbmduowftgppigklqlvqdcqexloqkedphquchrjeyytjhhuxutqxxhdxutogxuxhntjulvbmuvwfftfanwyogemcxekxyifmcqjqmldkjcpqwuqmrpbbvqdtwnrvvwkbqvtdjynucdlbbdpuurvrkbnhoifnhrqxnmcalrupxjsyojtjdsdnttwlceylvrkleolrgj";

        Assertions.assertEquals(-1,PalindromeIndex.with(s));
    }

    @Test
    @DisplayName("Return 44 When PalindromeIndex With 'hgygsvlfcwnswtuhmya...'")
    public void test12() {

        String s = "hgygsvlfcwnswtuhmyaljkqlqjjqlqkjlaymhutwsnwcwflvsgygh";

        Assertions.assertEquals(44,PalindromeIndex.with(s));
    }



}