
name: GFR-JUDGES-ONLINE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0.292'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true

#  test:
#    runs-on: ubuntu-latest
#    needs: [build]
#    steps:
#      - name: Clean
#        run: mvn clean
#
#      - name: Tests
#        run: mvn test
#
#  test_mutation:
#    runs-on: ubuntu-latest
#    needs: [build]
#    steps:
#      - name: Mutation tests
#        run: mvn org.pitest:pitest-maven:mutationCoverage
#
#  verify_archive_publish_deploy:
#    runs-on: ubuntu-latest
#    needs: [test,test_mutation]
#    steps:
#      - name: Verify Phase
#        run: mvn verify
#
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: junit
#          path: |
#            target/surefire-reports
#            !target/**/*.txt
#
#      - name: Archive code coverage results
#        uses: actions/upload-artifact@v2
#        with:
#          name: code-coverage-report
#          path: target/pit-reports
#
#      - name: Publish Unit Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v1
#        if: always()
#        with:
#          files: target/surefire-reports/*.xml
#
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        if: always()
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./target/pit-reports/*/
